application: cloud-training-
api_version: alpha003
runtime: python27
version: 1
threadsafe: true

handlers:
- url: /user/.*
  script: main.app
  login: required
  secure: always

- url: /.*
  script: main.app
  login: required
  secure: always