application: cloud-training-144023
version: alpha003
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /user/.*
  script: main.app
  login: required
  secure: always

- url: /.*
  script: main.app
  login: required
  secure: always
